### ISSUE TITLE
ip6tables entry

### ISSUE THREAD

**Issue by mpqo** [Magisk-Modules-Repo/dnscrypt-proxy-magisk#11] opened 2018-04-14 16:33 UTC
Hey @bluemeda, 

Today I've connected to an access point that allocates ipv6 DNS entries for first time. 

Resulting my phone was failing to use dnscrypt servers and used ipv6 DNS servers came from dhcp as it was first in line before the v4 DNS servers. 

I've fixed that by modifying service.sh and simply adding the following two ipv6 iptables (ip6tables) entries :

ip6tables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination [::1]:5354
ip6tables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination [::1]:5354 

You may consider to add it. 

PS: dnscrypt 2.0.9 is out :)

![screenshot_2018-04-14-22-09-22](https://user-images.githubusercontent.com/3320229/38771716-a1209d96-4030-11e8-8fc0-2ad0e3273a52.png)

**Comment by pwsnla** [comment] 2018-04-16 09:48
This is an exact duplicate of issue #10 I logged a few days ago. What's interesting is that I also tried adding IP6TABLES entries you listed but it did not fix the problem for me. My phone is NOT using dnscrypt when on IPv6 connection. Did you make any other changes in dncrypt config besides setting ipv6_servers = true?

**Comment by pwsnla** [comment] 2018-04-16 12:55
I figured out why IP6TABLES command did not work on my phone but I am not sure how to fix it. It turns out that I don't have 'nat' table in IP6TABLES. Using '-t nat' with IP6TABLES returns an error:

ip6tables v1.6.1: can't initialize ip6tables table `nat`: table does not exist  (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.

I do have `filter` and `mangle' in ip6tables but no `nat'. My knowledge of networking is certainly too limited to understand how to fix it. I've read that nat for IPv6 is not necessary but I am not sure if I can do what needs to be done here without it or how to get nat table installed. If anyone has any suggestions please let me know.

**Comment by mpqo** [comment] 2018-04-16 17:03
![screenshot_2018-04-16-20-01-16](https://user-images.githubusercontent.com/3320229/38824197-1e2db586-41b1-11e8-850d-37def4bc9837.png)

@pwsnla If your iptables is incompatible you can't do much. Maybe you can consider changing rom/kernel.

**Comment by bluemeda** [comment] 2018-04-17 05:44
@pwsnla as described by @mpqo, iptables compatibility depends on kernel modules. Try to change another kernel.

**Comment by bluemeda** [comment] 2018-04-17 09:24
Just try the new version and please give feedback.

**Comment by mpqo** [comment] 2018-04-17 16:13
@bluemeda 

IPtables are created both for v4 and v6, seems to work just fine for me:)

**Closed** 2018-05-15 04:26 UTC
